includes:
- /etc$
- /etc/passwd
- /etc/group
- /etc/shadow
- /etc/gshadow
steps: 
  - useradd -d "/home/live"  -c "live user" -g root -G wheel,sudoers -m -N -p "$(openssl passwd -1 -salt xyz live )" -s /bin/bash live
unpack: true
requires:
- category: "derivOS"
  name: "Noyau"
  version: ">=0"