excludes: 
- ^/etc/passwd
- ^/etc/shadow
- ^/etc/group
- ^/etc/gshadow

steps:
- apt-get update
- DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 lightdm
  
requires:
- category: "derivOS"
  name: "Seed"
  version: ">=0"