excludes: 
- ^/etc/passwd
- ^/etc/shadow
- ^/etc/group
- ^/etc/gshadow

steps:
- apt-get update
- DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 lightdm
- DEBIAN_FRONTEND=noninteractive apt-get install -y linux-image-amd64 
- DEBIAN_FRONTEND=noninteractive apt-get install -y dracut dracut-live ||true
- dracut --kver $(ls /lib/modules) -N -a dmsquash-live -a pollcdrom -a systemd -a systemd-initrd -a systemd-networkd  -a dracut-systemd --force
- cp /boot/initrd.img-*-amd64 /boot/initrd-dracut
- cp /boot/vmlinuz-*-amd64 /boot/vmlinuz

  
requires:
- category: "derivOS"
  name: "Seed"
  version: ">=0"